import 'package:flutter/material.dart';
import 'package:eventak/core/constants/app-colors.dart';
import '../data/todo_service.dart';
import '../data/todo_model.dart';
import '../widgets/todo_list_tile.dart';
import '../widgets/create_todo_dialog.dart';

class TodoListView extends StatefulWidget {
  final int eventId;
  const TodoListView({super.key, required this.eventId});

  @override
  State<TodoListView> createState() => _TodoListViewState();
}

class _TodoListViewState extends State<TodoListView> {
  final TodoService _todoService = TodoService();
  List<TodoItem> _currentTodos = [];
  late Future<List<TodoItem>> _todoFuture;

  int? filterIsCompleted;
  String? filterPriority;
  int? filterIsAutoGenerated;

  @override
  void initState() {
    super.initState();
    _applyFilters();
  }

  void _applyFilters() {
    setState(() {
      _todoFuture = _todoService.fetchTodos(
        widget.eventId,
        isCompleted: filterIsCompleted,
        priority: filterPriority,
        isAutoGenerated: filterIsAutoGenerated,
      ).then((value) {
        _currentTodos = value;
        return value;
      });
    });
  }

  void _showCreateDialog() {
    showDialog(
      context: context,
      builder: (context) => CreateTodoDialog(
        eventId: widget.eventId,
        currentTaskCount: _currentTodos.length,
        onSuccess: _applyFilters,
      ),
    );
  }

  Future<void> _handleDelete(int todoId) async {
    bool? confirm = await showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Task?'),
        content: const Text('Are you sure you want to remove this task?'),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Cancel')),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('Delete', style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );

    if (confirm == true) {
      final success = await _todoService.deleteTodo(widget.eventId, todoId);
      if (success && mounted) _applyFilters();
    }
  }

  Widget _buildFilterBar() {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      child: Row(
        children: [
          FilterChip(
            label: const Text("Completed"),
            selected: filterIsCompleted == 1,
            selectedColor: AppColor.primary.withOpacity(0.2),
            onSelected: (val) {
              setState(() => filterIsCompleted = val ? 1 : null);
              _applyFilters();
            },
          ),
          const SizedBox(width: 8),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
              border: Border.all(color: Colors.grey.shade300),
            ),
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                hint: const Text("Priority"),
                value: filterPriority,
                items: ["high", "medium", "low"].map((p) => 
                  DropdownMenuItem(value: p, child: Text(p.toUpperCase()))).toList(),
                onChanged: (val) {
                  setState(() => filterPriority = val);
                  _applyFilters();
                },
              ),
            ),
          ),
          const SizedBox(width: 8),
          FilterChip(
            label: const Text("Auto-Generated"),
            selected: filterIsAutoGenerated == 1,
            selectedColor: AppColor.primary.withOpacity(0.2),
            onSelected: (val) {
              setState(() => filterIsAutoGenerated = val ? 1 : null);
              _applyFilters();
            },
          ),
          if (filterIsCompleted != null || filterPriority != null || filterIsAutoGenerated != null)
            IconButton(
              icon: const Icon(Icons.close, color: Colors.red),
              onPressed: () {
                setState(() {
                  filterIsCompleted = null;
                  filterPriority = null;
                  filterIsAutoGenerated = null;
                });
                _applyFilters();
              },
            ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('To-Do List'),
        centerTitle: true,
        backgroundColor: Colors.white,
        foregroundColor: AppColor.blueFont,
        elevation: 0,
      ),
      body: Column(
        children: [
          _buildFilterBar(), 
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 4, 16, 8),
            child: Align(
              alignment: Alignment.topRight,
              child: SizedBox(
                height: 36,
                child: ElevatedButton.icon(
                  onPressed: _showCreateDialog,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColor.primary,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                  ),
                  icon: const Icon(Icons.add, size: 18),
                  label: const Text('Create', style: TextStyle(fontSize: 14)),
                ),
              ),
            ),
          ),
          Expanded(
            child: FutureBuilder<List<TodoItem>>(
              future: _todoFuture,
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                } else if (snapshot.hasError) {
                  return Center(child: Text('Error: ${snapshot.error}'));
                } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
                  return const Center(child: Text('No tasks matching these filters.'));
                }

                return RefreshIndicator(
                  onRefresh: () async => _applyFilters(),
                  child: ListView.builder(
                    itemCount: snapshot.data!.length,
                    padding: const EdgeInsets.all(16),
                    itemBuilder: (context, index) {
                      final todo = snapshot.data![index];
                      return TodoListTile(
                        todo: todo,
                        onDelete: () => _handleDelete(todo.id),
                        onToggle: () async {
                          final ok = await _todoService.toggleTodoCompletion(widget.eventId, todo.id);
                          if (ok && mounted) _applyFilters();
                        },
                      );
                    },
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}