import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:eventak/core/constants/api_constants.dart';
import 'todo_model.dart';

class TodoService {
Future<List<TodoItem>> fetchTodos(int eventId, {
  int? isCompleted,
  String? priority,
  int? isAutoGenerated,
}) async {
  final prefs = await SharedPreferences.getInstance();
  final token = prefs.getString('auth_token')?.replaceAll('"', '');

  Map<String, String> queryParams = {};
  if (isCompleted != null) queryParams['is_completed'] = isCompleted.toString();
  if (priority != null) queryParams['priority'] = priority;
  if (isAutoGenerated != null) queryParams['is_auto_generated'] = isAutoGenerated.toString();

  final uri = Uri.parse('${ApiConstants.baseUrl}/events/$eventId/todos')
      .replace(queryParameters: queryParams);

  final response = await http.get(
    uri,
    headers: {
      'Accept': 'application/json',
      'Authorization': 'Bearer $token',
    },
  );

  if (response.statusCode == 200) {
    final Map<String, dynamic> decoded = jsonDecode(response.body);
    final List<dynamic> todoList = decoded['data']['todos'];
    return todoList.map((json) => TodoItem.fromJson(json)).toList();
  } else {
    throw Exception('Failed to load filtered todos');
  }
}
Future<bool> createTodo(int eventId, Map<String, dynamic> data) async {
  final prefs = await SharedPreferences.getInstance();
  final token = prefs.getString('auth_token')?.replaceAll('"', '');

  final response = await http.post(
    Uri.parse('${ApiConstants.baseUrl}/events/$eventId/todos'),
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      'Authorization': 'Bearer $token',
    },
    body: jsonEncode(data),
  );

  return response.statusCode == 200 || response.statusCode == 201;
}
Future<bool> deleteTodo(int eventId, int todoId) async {
  final prefs = await SharedPreferences.getInstance();
  final token = prefs.getString('auth_token')?.replaceAll('"', '');

  final response = await http.delete(
    Uri.parse('${ApiConstants.baseUrl}/events/$eventId/todos/$todoId'),
    headers: {
      'Accept': 'application/json',
      'Authorization': 'Bearer $token',
    },
  );

  return response.statusCode == 200 || response.statusCode == 204;
  }
Future<bool> toggleTodoCompletion(int eventId, int todoId) async {
  final prefs = await SharedPreferences.getInstance();
  final token = prefs.getString('auth_token')?.replaceAll('"', '');

  final response = await http.post(
    Uri.parse('${ApiConstants.baseUrl}/events/$eventId/todos/$todoId/toggle-completion'),
    headers: {
      'Accept': 'application/json',
      'Authorization': 'Bearer $token',
    },
  );

  return response.statusCode == 200;
  }
Future<bool> reorderTodos(int eventId, List<int> orderedIds) async {
  final prefs = await SharedPreferences.getInstance();
  final token = prefs.getString('auth_token')?.replaceAll('"', '');

  final response = await http.post(
    Uri.parse('${ApiConstants.baseUrl}/events/$eventId/todos/reorder'),
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      'Authorization': 'Bearer $token',
    },
    body: jsonEncode({
      "ordered_ids": orderedIds, 
    }),
  );

  return response.statusCode == 200;
}
}